[project]
version = "3.0.0"
name = "spsdk_plugins"

[tool.release-tools]
disabled = ['docs']
sub_projects = [ "codecheck" ]

[tool.release-tools.scr]
scr_file = "SW_Content_Register_SPSDK_plugins.txt"