[project]
version = "3.0.0"
name = "spsdk_plugins"

[tool.release-tools]
disabled = ['docs']
sub_projects = [ "codecheck", "keyfactor", "jlink", "mcu_link", "lauterbach", "pemicro", "pkcs11", "pqc", "pylint_plugins", "pyocd" ]

[tool.release-tools.scr]
scr_file = "SW_Content_Register_SPSDK_plugins.txt"