name: Publish To PyPi

on:
  pull_request:
    branches: ["main"]
  push:
    tags:
      - 'v*'

jobs:
  get-packages:
    name: Get Package List
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python TOML parser
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - id: get-packages
        run: |
          python -c "import toml; print('packages=' + str(toml.load('pyproject.toml')['tool']['release-tools']['clr']['package_directories']))" >> $GITHUB_OUTPUT

  package:
    name: Build Packages
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    strategy:
      matrix:
        package: ${{fromJson(needs.get-packages.outputs.packages)}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and Check Package
        uses: hynek/build-and-inspect-python-package@v2.8.0
        with:
          path: ${{ matrix.package }}
          attest-build-provenance-github: 'true'

  deploy:
    name: Upload Releases To PyPI
    needs: [package]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Download Packages
      uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist

    #- name: Publish packages to PyPI
    #  uses: pypa/gh-action-pypi-publish@v1.9.0
